"""
Step 4-2: 어셈블리 테스트 코드 생성 (4회 미팅 액션 아이템)

각 명령어(Instruction)에 대해 operand 타입을 실제 레지스터/값으로 치환하여
랜덤하게 10개씩 어셈블리 코드를 생성합니다.

미팅 규칙:
- 첫 줄: .intel_syntax noprefix  (Intel 문법, 접두어 없음)
- 상수(IMM): 최대값 사용 (0xFF, 0xFFFF 등)
- 메모리: Effective Addressing + RIP-relative 혼합
- 메모리 크기: BYTE PTR / WORD PTR / DWORD PTR / QWORD PTR 명시
- 생성 횟수: 약 10회 랜덤 (mitigates combinatorial explosion)
"""

import pandas as pd
import random
import re
from pathlib import Path

# 같은 패키지의 그룹 정의 재사용
import sys
sys.path.insert(0, str(Path(__file__).parent))
from step4_operand_grouping import OPERAND_GROUPS, parse_instruction, get_operand_candidates

random.seed(42)  # 재현 가능성 위해 seed 고정

N_RANDOM = 10   # 명령어당 생성할 랜덤 케이스 수


def generate_test_lines(mnemonic: str, operand_tokens: list, n: int = N_RANDOM):
    """
    (mnemonic, operand_tokens)를 받아 구체적인 어셈블리 라인 n개 생성.
    operand 없으면 mnemonic만 반환.
    """
    if not operand_tokens:
        return [mnemonic.lower()]

    candidate_lists = [get_operand_candidates(tok) for tok in operand_tokens]

    results = []
    seen = set()
    attempts = 0

    while len(results) < n and attempts < n * 20:
        chosen = [random.choice(cl) for cl in candidate_lists]
        line = mnemonic.lower() + " " + ", ".join(chosen)
        if line not in seen:
            seen.add(line)
            results.append(line)
        attempts += 1

    return results if results else [mnemonic.lower()]


def build_asm_file(instructions_df: pd.DataFrame, output_path: Path, n_per_instr: int = N_RANDOM):
    """
    파싱된 명령어 DataFrame으로부터 어셈블리 테스트 파일(.s) 생성.
    각 라인 옆에 원본 Instruction을 주석으로 표시.
    """
    lines = []
    lines.append(".intel_syntax noprefix")
    lines.append("# Auto-generated Intel assembly test file")
    lines.append("# Generated by step4_test_generator.py")
    lines.append("# Rules: IMM=MAX_VALUE, MEM=EFFECTIVE/RIP_RELATIVE, BYTE/WORD/DWORD/QWORD PTR")
    lines.append("")

    total_cases = 0
    unique_instrs = 0

    # 중복 제거: (mnemonic, operand_tokens) 기준
    seen_forms = set()

    for _, row in instructions_df.iterrows():
        instr_str = row["Instruction"]
        mnemonic, tokens = parse_instruction(str(instr_str))
        form_key = (mnemonic, tuple(tokens))

        if form_key in seen_forms:
            continue
        seen_forms.add(form_key)

        test_lines = generate_test_lines(mnemonic, tokens, n=n_per_instr)
        unique_instrs += 1

        lines.append(f"# === {instr_str} ===")
        for tl in test_lines:
            lines.append(f"    {tl}")
            total_cases += 1
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return total_cases, unique_instrs


def main():
    base = Path(__file__).parent.parent.parent
    stage4_dir = base / "data" / "stage4_tests"
    stage4_dir.mkdir(parents=True, exist_ok=True)

    parsed_csv = stage4_dir / "step4_instructions_parsed.csv"

    print("=" * 60)
    print("Step 4-2: 어셈블리 테스트 코드 생성")
    print("=" * 60)

    if not parsed_csv.exists():
        print(f"[오류] {parsed_csv} 없음. step4_operand_grouping.py 먼저 실행하세요.")
        return

    df = pd.read_csv(parsed_csv, encoding="utf-8")
    print(f"[로드] 파싱된 명령어: {len(df)}개")

    # 전체 통합 테스트 파일
    all_asm_path = stage4_dir / "test_all_instructions.s"
    total_cases, unique_instrs = build_asm_file(df, all_asm_path)
    print(f"\n[완료] 전체 테스트 파일: {all_asm_path}")
    print(f"  - 고유 명령어 형태: {unique_instrs}개")
    print(f"  - 생성된 테스트 케이스: {total_cases}개")

    # 미리보기 출력
    preview_lines = all_asm_path.read_text(encoding="utf-8").split("\n")[:40]
    print("\n=== 파일 미리보기 (앞 40줄) ===")
    for i, l in enumerate(preview_lines, 1):
        print(f"{i:3d} | {l}")

    print(f"\n[완료] Step 4-2 테스트 코드 생성 완료")
    print(f"      → {all_asm_path}")


if __name__ == "__main__":
    main()
